"""
Text Splitter Helper - Shared logic for chunking text.

Provides common functionality for chunking both files and queries,
making it reusable across different pipelines.
"""

import aiofiles
from typing import List, Tuple, Optional, Dict

from llama_index.core.node_parser import CodeSplitter, MarkdownNodeParser, SentenceSplitter
from llama_index.core.schema import Document, TextNode


class TextSplitterHelper:
    """
    Helper class for text chunking operations.

    Configuration can be provided via constructor. If not provided,
    default values from config/base.py are used.
    """

    def __init__(
        self,
        python_chunk_lines: int = 40,
        python_chunk_overlap: int = 15,
        python_max_chars: int = 1500,
        doc_chunk_size: int = 512,
        doc_chunk_overlap: int = 50,
        config_chunk_size: int = 512,
        config_chunk_overlap: int = 50,
    ) -> None:
        self.python_chunk_lines = python_chunk_lines
        self.python_chunk_overlap = python_chunk_overlap
        self.python_max_chars = python_max_chars
        self.doc_chunk_size = doc_chunk_size
        self.doc_chunk_overlap = doc_chunk_overlap
        self.config_chunk_size = config_chunk_size
        self.config_chunk_overlap = config_chunk_overlap

    def create_splitter(self, extension: str):
        """Creates a splitter based on file extension using configured parameters."""
        if extension == ".py":
            return "code", CodeSplitter(
                language="python",
                chunk_lines=self.python_chunk_lines,
                chunk_lines_overlap=self.python_chunk_overlap,
                max_chars=self.python_max_chars,
            )
        elif extension == ".md":
            return "doc", MarkdownNodeParser()
        elif extension in {".yaml", ".yml", ".toml"}:
            return "config", SentenceSplitter(
                chunk_size=self.config_chunk_size,
                chunk_overlap=self.config_chunk_overlap,
            )
        else:
            return "text", SentenceSplitter(
                chunk_size=self.doc_chunk_size,
                chunk_overlap=self.doc_chunk_overlap,
            )

    async def chunk_file(
        self,
        file_path: str,
        relative_path: str,
        extension: str,
    ) -> Tuple[List[TextNode], Optional[str]]:
        """
        Chunks a file using the appropriate splitter.

        Args:
            file_path: Absolute path to the file
            relative_path: Relative path (for metadata)
            extension: File extension (including dot)

        Returns:
            Tuple of (nodes, error). nodes is List[TextNode], error is None on success.
        """
        # Read file
        encodings = ['utf-8', 'utf-8-sig', 'latin-1', 'cp1252', 'iso-8859-1']
        content = None
        error = None

        for encoding in encodings:
            try:
                async with aiofiles.open(file_path, 'r', encoding=encoding, errors='strict') as f:
                    content = await f.read()
                if '\x00' in content:
                    return [], f"binary file (contains null bytes): {relative_path}"
                break
            except UnicodeDecodeError:
                continue
            except FileNotFoundError:
                return [], f"File not found: {relative_path}"
            except PermissionError:
                return [], f"Permission denied: {relative_path}"
            except Exception as e:
                error = f"Failed to read {relative_path} with encoding {encoding}: {e}"
                continue

        if content is None:
            return [], error or f"Failed to read {relative_path}"

        # Create splitter using instance configuration
        chunk_type, splitter = self.create_splitter(extension)

        try:
            nodes = splitter.get_nodes_from_documents([
                Document(
                    text=content,
                    metadata={
                        "file_path": relative_path,
                        "extension": extension,
                    },
                )
            ])
        except Exception as e:
            return [], f"Failed to split file {relative_path}: {e}"

        # Enrich node metadata
        for idx, node in enumerate(nodes):
            node.metadata["file_path"] = relative_path
            node.metadata["extension"] = extension
            node.metadata["chunk_type"] = chunk_type
            node.metadata["chunk_index"] = idx
            # Note: node_id will be auto-generated by vector store

        return nodes, None

    async def chunk_text(
        self,
        text: str,
        splitter,
        chunk_type: str = "text",
        metadata: Optional[Dict] = None,
    ) -> Tuple[List[Dict], Optional[str]]:
        """
        Chunk raw text using a given splitter.

        Args:
            text: Input text to chunk
            splitter: LlamaIndex splitter instance (SentenceSplitter, CodeSplitter, etc.)
            chunk_type: Type identifier for chunks
            metadata: Optional metadata to attach to each chunk

        Returns:
            Tuple of (chunks, error). chunks is List[Dict] with keys: content, metadata, chunk_type.
        """
        if not text or not text.strip():
            return [], "Empty text provided"

        try:
            nodes = splitter.get_nodes_from_documents([
                Document(
                    text=text,
                    metadata=metadata or {},
                )
            ])
        except Exception as e:
            return [], f"Failed to split text: {e}"

        # Convert TextNode to simple dict format
        chunks = []
        for idx, node in enumerate(nodes):
            chunk_meta = dict(node.metadata or {})
            chunk_meta["chunk_index"] = idx
            chunk_meta["chunk_type"] = chunk_type
            
            chunks.append({
                "content": node.text,
                "metadata": chunk_meta,
                "chunk_type": chunk_type,
            })

        return chunks, None

    def split_query_by_sentences(self, text: str, max_chars: int = 2000) -> Tuple[List[str], Optional[str]]:
        """
        Split query into sentence-based chunks respecting max_chars limit.
        
        Used for query chunking when simple sentence splitting is sufficient.

        Args:
            text: Query text to split
            max_chars: Maximum characters per chunk (default 2000)

        Returns:
            Tuple of (chunks, error). chunks is List[str].
        """
        if not text or not text.strip():
            return [], "Empty text provided"

        # Simple sentence splitting
        sentences = []
        current_chunk = ""
        
        # Split by sentence boundaries
        for sentence in text.replace('!', '.').replace('?', '.').split('.'):
            sentence = sentence.strip()
            if not sentence:
                continue
                
            # If adding this sentence would exceed limit, save current chunk
            if current_chunk and len(current_chunk) + len(sentence) + 1 > max_chars:
                sentences.append(current_chunk.strip())
                current_chunk = sentence + "."
            else:
                if current_chunk:
                    current_chunk += " " + sentence + "."
                else:
                    current_chunk = sentence + "."
        
        # Add final chunk
        if current_chunk:
            sentences.append(current_chunk.strip())

        # If no chunks created (text too long or no sentences), return original text
        if not sentences:
            return [text], None

        return sentences, None
