"""
Text Splitter Helper - Shared logic for chunking text.

Provides common functionality for chunking both files and queries,
making it reusable across different pipelines.
"""

import aiofiles
from typing import List, Tuple, Optional

from llama_index.core.node_parser import CodeSplitter, MarkdownNodeParser, SentenceSplitter
from llama_index.core.schema import Document, TextNode


class TextSplitterHelper:
    """
    Helper class for text chunking operations.
    """
    
    @staticmethod
    def create_splitter(extension: str):
        """Creates a splitter based on file extension."""
        if extension == ".py":
            return "code", CodeSplitter(
                language="python",
                chunk_lines=40,
                chunk_lines_overlap=15,
                max_chars=1500,
            )
        elif extension == ".md":
            return "doc", MarkdownNodeParser()
        elif extension in {".yaml", ".yml", ".toml"}:
            return "config", SentenceSplitter(
                chunk_size=512,
                chunk_overlap=50,
            )
        else:
            return "text", SentenceSplitter(
                chunk_size=512,
                chunk_overlap=50,
            )
    
    @staticmethod
    async def chunk_file(
        file_path: str,
        relative_path: str,
        extension: str,
    ) -> Tuple[List[TextNode], Optional[str]]:
        """
        Chunks a file using the appropriate splitter.
        
        Returns:
            Tuple of (nodes, error). nodes is List[TextNode], error is None on success.
        """
        # Read file
        encodings = ['utf-8', 'utf-8-sig', 'latin-1', 'cp1252', 'iso-8859-1']
        content = None
        error = None
        
        for encoding in encodings:
            try:
                async with aiofiles.open(file_path, 'r', encoding=encoding, errors='strict') as f:
                    content = await f.read()
                if '\x00' in content:
                    return [], f"binary file (contains null bytes): {relative_path}"
                break
            except UnicodeDecodeError:
                continue
            except FileNotFoundError:
                return [], f"File not found: {relative_path}"
            except PermissionError:
                return [], f"Permission denied: {relative_path}"
            except Exception as e:
                error = f"Failed to read {relative_path} with encoding {encoding}: {e}"
                continue
        
        if content is None:
            return [], error or f"Failed to read {relative_path}"
        
        # Create splitter
        chunk_type, splitter = TextSplitterHelper.create_splitter(extension)
        
        try:
            nodes = splitter.get_nodes_from_documents([
                Document(
                    text=content,
                    metadata={
                        "file_path": relative_path,
                        "extension": extension,
                    },
                )
            ])
        except Exception as e:
            return [], f"Failed to split file {relative_path}: {e}"
        
        # Enrich node metadata
        for idx, node in enumerate(nodes):
            node.metadata["file_path"] = relative_path
            node.metadata["extension"] = extension
            node.metadata["chunk_type"] = chunk_type
            node.metadata["chunk_index"] = idx
            # Note: node_id will be auto-generated by vector store
        
        return nodes, None
